### ISSUE TITLE
Invalid parameter in getDocument

### ISSUE THREAD

**Issue by ramirez** [winkerVSbecks/angular-pdf-viewer#10]
Hi,

I keep getting "Invalid parameter in getDocument, need either Uint8Array, string or a parameter object" in here: (angular-pdf-viewer.min.js:1:2279) when adding an instance of pdf-viewer to my code. It doesn't matter what I pass as url parameter. Any ideas why can this be happening?

Thx!

L.

**Comment by winkerVSbecks** [comment]
@ramirez what version of the angular-pdf-viewer are you using? Also, can you post your directive and controller code here. Thanks!

**Comment by ramirez** [comment]
Hi,

thanks for the quick reply. After checking the code, I realized that I was passing a {{}} expression with some scope variable as url, so the $scope.$eval of the attribute was failing. I removed the {{}} and it worked. Thx!

L.
