### ISSUE TITLE
when window resize

### ISSUE THREAD

**Issue by sumomostudio** [winkerVSbecks/angular-pdf-viewer#11]
when browser window resizes, the pdf (canvas) won't resize accordingly.
are there any options that I might miss to enable resizing?

now I modified the <canvas></canvas> part into

<canvas style="width:100%"></canvas>

then, it works ok. however is this a 'good' solution?

**Comment by winkerVSbecks** [comment]
That's how canvas works. You need to trigger a refresh on window resize. You can make the actual `<canvas>` element responsive with pure CSS. However,you will still have to handle resizing/refreshing it's [render context](https://developer.mozilla.org/en/docs/Web/API/CanvasRenderingContext2D).

I'm not aware of anyway to support autoresizing of the context.
