### ISSUE TITLE
Delegate handle not working as binding

### ISSUE THREAD

**Issue by parliament718** [winkerVSbecks/angular-pdf-viewer#12]
I'm going to have multiple pdfs on a page so I'm trying to set the delegate-handle using an angular expression like so:

 ```<pdf-viewer url="file.FileLocation" delegate-handle="{{ file.Key }}" scale="1" show-toolbar="true"></pdf-viewer>```

However I when I try to use the toolbar I get:

Delegate for handle "the-resulting-file-key" could not find a corresponding element with delegate-handle="the-resulting-file-key"

It works if I set delegate-handle to a static string, but I need it dynamic.

**Comment by winkerVSbecks** [comment]
It's evaluated within the directive. It should be written as: `delegate-handle="file.Key"`

**Comment by parliament718** [comment]
my mistake. I tried that but didn't work earlier, must've been some other mistake, it works now. Thanks.
