### ISSUE TITLE
Improvement: onloaded callback

### ISSUE THREAD

**Issue by igorlino** [winkerVSbecks/angular-pdf-viewer#13]
when loading a PDF from an URL or even from a file, it takes some time before some methods from the delegate are usable. (i.e. getCount , etc)

A simple improvement could help getting an update from an optional 'onloaded' method, when a resource is loading completed.

Thanks,
-Igor

**Comment by winkerVSbecks** [comment]
Sounds like a good idea. I'll add it to the next release.

**Comment by winkerVSbecks** [comment]
@igorlino this has been delivered thanks to @newrdev's PR. The `load` function return a promise now. You can chain onto it to ensure that the PDF did load. Example:

```js
myPdf
  .load('url-of-the-new-file.pdf')
  .then(function()) {
    myPdf. getPageCount()
   });
```

**Comment by igorlino** [comment]
Great!, will try it out. This should help to fix some exceptions in the browser.

**Comment by sesamechicken** [comment]
This promise works beautifully! Thanks!

**Comment by JohannesHoffmann** [comment]
How to get the Callback on the first loaded PDF via the attribute url="pdfUrl".
I am loading the PDFs from a external webserver. I need a callback for success to hide the spinner and a callback when it fails for a small error message. I don't reload the file i just need a simple callbacks success and errors for the first loaded pdf via the url attribute.

how is this going? thankgs for help ;)

**Comment by winkerVSbecks** [comment]
@JohannesHoffmann It's exactly as you described it:

```
pdfDelegate.$getByHandle('your-handle')
  .load($scope.pdfUrl)
  .then(function() {
    $scope.onSuccess();
  })
  .catch(function() {
    $scope.onError();
  });
```

All directives are isolated scopes (recommended best practice for Angular 1.x). Therefore, they can't just call `$scope.onSuccess`. A promise is being exposed to you which makes it easy to attach callbacks.
