### ISSUE TITLE
Improvement: sexy demo

### ISSUE THREAD

**Issue by igorlino** [winkerVSbecks/angular-pdf-viewer#14]
Hi,

Still, playing around with the pdf topic. Something that I feel is missing, looking at all the alternatives, is a more sexy demo.
Something like http://mozilla.github.io/pdf.js/web/viewer.html

Looking at the html code of that demo, they additionally use the http://mozilla.github.io/pdf.js/web/viewer.js

The interesting features it has are:
* A more complete toolbar 
* A very nice navigation/preview panel to the left.
* The black-band-style looks interesting, considering the contrast to document reading.

So perhaps this is something you already considered, therefore my questions:
1) What is missing for that kind of demo to be angular-based ?  (what I have in mind : the viewer.js cannot be used as it is, and needs to be converted into an own directive)
2) Is this the kind of direction the angular-pdf-viewer could/would go into ?
(what I have in mind: probably yes, as this would this angular directive a killer feature, which would imply a bit of effort, if to decrease the effort, maybe one can make a wrapper around it)

**Comment by winkerVSbecks** [comment]
@igorlino to be honest this is beyond the scope of this project. 

The main `pdf` is controllable through the delegates. Therefore, You can potentially replicate the demo by building your own custom toolbar – see issue #15 for more info.

**Comment by igorlino** [comment]
@winkerVSbecks thanks for the answer. yes, I understand. ( BTW I have created some weeks ago a custom toolbar and a very interesting page navigation with animation effects. )
I'm not sure the delegate is ATM powerful enough to handle all the goodies that has the viewer.js application.

I will give it a though over the next weeks/months, if I do it at all, and with which tech stack.
I'm having strong thoughts in doing it in TypeScript, but it all depends on my time availability and if there is a real client for it.
