### ISSUE TITLE
Error: Invalid parameter object: need either .data, .range or .url

### ISSUE THREAD

**Issue by FrancescoMussi** [winkerVSbecks/angular-pdf-viewer#16]
Before i have tested the directive with the sample file and it was working fine.

I am trying now to make it working with my own files, both in localhost and on the server.
It isn't working. In both cases i am getting the following error:

    Error: Invalid parameter object: need either .data, .range or .url

The only thing i have done is the following:  change the link from 

$scope.pdfUrl = 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/149125/relativity.pdf';

to

$scope.pdfUrl = base_url + 'data/drawer/' + $scope.file.data_id + '/' + $scope.file.filename;

if i open the path of  $scope.file_url in the browser it will properly display the pdf file, both in locahost and online.

Why am i getting the error?
What am i doing wrong?

Thank you very much!

**Comment by winkerVSbecks** [comment]
Can you post more of your code. Where do you have this expression – in a controller, directive, etc.? Is the `file` object loaded asynchronously? 

How are you passing `pdfUrl` it to the directive? Can you add a your template too. 

Also, can you try logging the `pdfUrl` inside [pdf-ctrl.js](https://github.com/winkerVSbecks/angular-pdf-viewer/blob/master/src/js/pdf-ctrl.js)

It seems like an issue where you are not passing the url correctly or it's not ready yet. 

Thanks

**Comment by FrancescoMussi** [comment]
Thanks @winkerVSbecks  for your time!
I am close to resolve this last thing and be able to use your very useful directive.

The file object is loaded asynchronously with a function initialize in the view through ng-init.
This is the function in the controller (the file path is currently hardcoded).
And in this way is not working.
This is the function in the controller:

$scope.get_file_detail = function()
	{
		var info_file = FileService.file_detail_get( $stateParams.file_id );
		info_file.then( function( data ) {

			$scope.file = data;
		        $scope.file_url = base_url + 'data/locahost/drawer/' + $scope.file.data_id + '/' + $scope.file.filename;
		 	
		});

    }


But if i hardcode the path directly into the controller then it is properly working:

$scope.file_url = 'http://localhost/sakura2/data/locahost/drawer/69/c649c4c8b5049486e66b0a52d01b00b1.PDF';

But i need to load the according to the id of the container and the file name.
Do you have any suggestion?

Thank you very much!
Definitely deserve a star

**Comment by FrancescoMussi** [comment]
I have make a question on SO about this:

http://stackoverflow.com/questions/29005509/angular-ng-init-function-loaded-after-directive

**Comment by winkerVSbecks** [comment]
@FrancescoMussi so, here's the issue. When the view loads `$scope.file_url` is null. The directive picks this up and since there is not binding it never gets the updated value.

`$scope.get_file_detail` runs later and updates the `$scope.file_url` value but, it's too late.


To get around this issue, wrap the directive in an `ng-if`. This way the directive will only load once the `file_url` is specified:

```html
<div ng-if="file_url">
  <pdf-viewer
      delegate-handle="my-pdf-container"
      url="file_url"
      scale="1"
      show-toolbar="false">
</div>
```

**Comment by FrancescoMussi** [comment]
Thank you very much for your help!
Now everything is working perfectly!
