### ISSUE TITLE
The delegate-handle is not found on my angular page using angular-ui-router

### ISSUE THREAD

**Issue by dusktreader** [winkerVSbecks/angular-pdf-viewer#18]
I'm adding a pdf viewer page to my app, and I'm trying to use angular-pdf-viewer, because it seems like it would be perfect. 

However, it will not load a pdf. When I load the 'pdfs' page, the controls appear at the top, but the canvas does not load a pdf. When I added a button to load the pdf manually, it still won't load and dumps this message to the console:
```
"Delegate for handle "my-pdf-container" could not find a corresponding element with delegate-handle="my-pdf-container"! load() was not called!
Possible cause: If you are calling load() immediately, and your element with delegate-handle="my-pdf-container" is a child of your controller, then your element may not be compiled yet. Put a $timeout around your call to load() and try again."
```
The same message is produced when ever I click on one of the navigation buttons built into the viewer.

My main app js looks like this:
```
'use strict';
 
 angular.module('myApp', [
     'ui.router',
     'ui.bootstrap',
     'pdf',
 ]).config(function ($stateProvider, $locationProvider, $provide, $httpProvider) {
 
     $stateProvider
         .state('home', {
             url: '/',
             templateUrl : '../webapp/views/home.html',
             controller: 'HomeCtrl',
             data: {
                 title: 'Empty home page'
             }
         })
         .state('pdfs', {
             url: '/pdfs',
             cache: false,
             templateUrl : '../webapp/views/pdfs.html',
             controller: 'PdfCtrl',
             data: {
                 title: 'Experimental system information page'
             }
         });

     $locationProvider.html5Mode({
         enabled: true,
         requireBase: false
     });
 
 }).run(function ($rootScope, $state, $http, $stateParams) {
     $rootScope.$stateParams = $stateParams;
 });
```

My PdfCtrl looks like this:
```
 angular.module('myApp')
 .controller('PdfCtrl', [ '$scope', 'pdfDelegate', '$timeout', function($scope, pdfDelegate, $timeout) {
     $scope.pdfUrl = '../webapp/pdfs/test.pdf';
     $scope.loadNewFile = function(url) {
         pdfDelegate
             .$getByHandle('my-pdf-container')
             .load(url);
     };
 }]);
```

and my pdfs.html looks like this:
```
 <site-frame style="display:block; height: 100%;">
 <pdf-viewer
         delegate-handle="my-pdf-container"
         url="pdfUrl"
         scale="1"
         show-toolbar="true"
         headers="{'x-you-know-whats-awesome': 'EVERYTHING'}"></pdf-viewer>
     <button class="btn btn-default" ng-click="loadNewFile('../webapp/pdfs/test.pdf')">Load</button>
 </site-frame>
```

Do you think this is an issue with angular-ui-router not cooperating with delegates? Could it be an angular version issue (1.3.14)?

**Comment by dusktreader** [comment]
I turns out that the issue is caused by using adding:
```'use strict';```

This causes the page to load without error, but no pdf is displayed.

When I excluded 'use strict', the pdf loads fine

**Comment by winkerVSbecks** [comment]
@dusktreader that probably means you are breaking some requirement of the [strict mode](http://ejohn.org/blog/ecmascript-5-strict-mode-json-and-more)

**Comment by dusktreader** [comment]
Well, I'm pretty sure it wasn't my code since every single script has 'use strict' at the beginning. Maybe you should check your app to make sure that it complies with strict Javascript. It makes no difference to me, I rolled my own pdf-viewer that wraps pdfjs.

**Comment by winkerVSbecks** [comment]
I'll look into it. Thanks
