### ISSUE TITLE
html5Mode(true) makes a lot of warnings and two errors in pdf.js and pdf.worker.js

### ISSUE THREAD

**Issue by dokenzy** [winkerVSbecks/angular-pdf-viewer#19]
Recently I set $locationProvider.html5Mode(true) in Angularjs 1.3.8, then a lot of warnings occur

    Warning: Ignoring invalid character "33" in hex string(pdf.worker.js)
    ...

and these errors

    Error: Invalid XRef stream header(pdf.worker.js)
    Warning: Unsupported feature "unknown"(pdf.worker.js)
    Warning: Unsupported feature "unknown"(pdf.js)
    Warning: Indexing all PDF objects(pdf.worker.js)
    Error: Invalid PDF structure(angular.js)

I guess the cause is in lower level rather than angular-dpf-viewer directive, but I have no idea how to deal with it.

Could you help me?

**Comment by winkerVSbecks** [comment]
@dokenzy I just tested the example with `$locationProvider.html5Mode(true)` – works fine. I'm guessing there is some other issue in your app.

**Comment by dokenzy** [comment]
Really? Hmm, I have to test my app again...
Thank you, winkerVSbecks.
