### ISSUE TITLE
Render all pages

### ISSUE THREAD

**Issue by maxxst** [winkerVSbecks/angular-pdf-viewer#20]
I need all document pages to render for a project. Is there a solution already or do I have to extend your viewer ?

**Comment by winkerVSbecks** [comment]
Just want to make sure I understand this correctly. You want to see all the pages at the same time – in a grid or scroll view? Yes, you would have to modify the directive. 

How many pages are we talking about? it might be insane to do that. The performance will be horrible.

**Comment by maxxst** [comment]
yes thats what I need - I figured it out so far .. but now I the reloads won't work xD

see https://github.com/juwit-team/angular-pdf-viewer

PS: we are talking about 1-10 pages

**Comment by winkerVSbecks** [comment]
Didn't realize they had a method for it. If you're up for it, you could add a flag for all pages vs one pages... and submit a PR

**Comment by maxxst** [comment]
they don't but you can loop through your render mechanism

question is only: how to handle rotation and that stuff ... -> still working on it :D

**Comment by winkerVSbecks** [comment]
What's the end result? Grid of pages or a vertical column?

In this case you won't be able to use CSS for rotation – all the pages are in one canvas. Instead you would have to draw the pages with rotation and translation within the canvas context. See this for an explanation: http://stackoverflow.com/a/4650102/1365008

I'm not sure if PDFJS exposes the raw context to you. So, the other option would be to have one canvas per page. Which might lead to performance issues.

**Comment by maxxst** [comment]
right now I have one canvas per page an I guess I'm working with that (at least for the moment)

I want to make the rotation and that stuff canvas specific and then I will send you a pull request :)

**Comment by winkerVSbecks** [comment]
That sounds like a UX challenge more than a technical one.

**Comment by maxxst** [comment]
so in the pdf.js repo they are also using a loop and multiple canvases https://github.com/mozilla/pdf.js/blob/master/examples/acroforms/forms.js#L142 so I guess it's the way to go
