### ISSUE TITLE
Parse error on amazon pdf file url

### ISSUE THREAD

**Issue by muhammad-irfan-arbisoft** [winkerVSbecks/angular-pdf-viewer#23]
I'm getting this error when try to render pdf file in angularjs app

`Error: [$parse:syntax] Syntax Error: Token ':' is an unexpected token at column 5 of the expression [http://pucdocket.s3.amazonaws.com/VA/PUE-2010-00039/122913.pdf] starting at [://pucdocket.s3.amazonaws.com/VA/PUE-2010-00039/122913.pdf].`

Here is pdf directive:

`<pdf-viewer
                                    delegate-handle="my-pdf-container"
                                    url="http://pucdocket.s3.amazonaws.com/VA/PUE-2010-00039/122913.pdf"
                                    scale="1"
                                    show-toolbar="true"
                                    ></pdf-viewer>`

**Comment by winkerVSbecks** [comment]
```
<pdf-viewer delegate-handle="my-pdf-container" 
                    url="'http://pucdocket.s3.amazonaws.com/VA/PUE-2010-00039/122913.pdf'" 
                    scale="1" 
                    show-toolbar="true" ></pdf-viewer>
```

Since, the url can be variable it is parsed within the directive. You need to wrap it with single quotes too. `" '... ' "`
