### ISSUE TITLE
Question: Can your directive load multiple PDFs in order?

### ISSUE THREAD

**Issue by ZachMoreno** [winkerVSbecks/angular-pdf-viewer#31]
If not, I can investigate adding a `loadMultiple()` method to the `pdfDelegate` or augmenting the existing `load()` method to accept multiple URLs as arguments. Or another option would be to add a promise that is fulfilled when `getPageCount() == getCurrentPage()`, then we could call the existing `load()` method to fetch the next URL.

**Comment by winkerVSbecks** [comment]
Would the multiple PDFs be rendered simultaneously? 
If you are simply cycling between PDFs then that would be better handled in a wrapper. Think list vs list item. This is more of a list item.

**Comment by ZachMoreno** [comment]
Yes, simultaneous rendering.
My agency often combines multiple PDFs into 1, prior to publishing.
I would like to use your directive to "combine" the PDFs on the fly, rather than using Acrobat.

**Comment by winkerVSbecks** [comment]
This isn't really setup to do that. You could build a wrapper that handles it, but I would recommend just tapping into PDF.js so you have more control over it. This directive is just a very shallow wrapper for PDF.js.

**Comment by ZachMoreno** [comment]
OK, thank you for responding promptly & clarifying.
If I come across opportunities to contribute to your project, I'll reach out as I'm happy to do so.

**Comment by winkerVSbecks** [comment]
:+1: thanks
