### ISSUE TITLE
'Access-Control-Allow-Origin' while using any PDF url

### ISSUE THREAD

**Issue by yashikagarg13** [winkerVSbecks/angular-pdf-viewer#32]
Hi

I want to use angular-pdf-viewer in my application. I was testing the plugin with some sample PDF links like this:

https://www.aeaweb.org/sample_references.pdf
http://www.urartuuniversity.com/content_images/pdf-sample.pdf

But every time I get this issue:

XMLHttpRequest cannot load https://www.aeaweb.org/sample_references.pdf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
angular.js:11699 Error: Unexpected server response (0) while retrieving PDF "https://www.aeaweb.org/sample_references.pdf"

Am I missing something? Pleas let me know.

**Comment by winkerVSbecks** [comment]
You have [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) issues. The server you are making requests to need to support CORS. This is not something that the directive or even PDFjs has control over. It's a security feature in Chrome (and most modern browsers).

**Comment by yashikagarg13** [comment]
ok thanks
