### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by ambinabhi** [winkerVSbecks/angular-pdf-viewer#44]
When the pdf is zoomed  till it goes out of the screen i am  not able to  move or scroll it horizontally. Any fix for that? Tried applying some css for the canvas and it didn't work. Any help would be much appreciated.

**Comment by winkerVSbecks** [comment]
Scrolling is handled purely through CSS. The canvas will resize when zooming in/out. It's the parent container for the canvas that needs to account for scrolling. http://tympanus.net/codrops/css_reference/overflow/
