### ISSUE TITLE
The image does not fit into the viewer after rotation

### ISSUE THREAD

**Issue by apiraino** [winkerVSbecks/angular-pdf-viewer#5]
Hi,

we are testing your viewer.
Apparently after a rotation the image is not properly fit into the viewer.

It seems the issue arise on the left side of the viewer and when the image has rectangular shape (thus one side much longer than the other).

If you need some more details, just let me know.

Thanks!

**Comment by winkerVSbecks** [comment]
@apiraino that sounds weird. The rotation is handled by CSS transforms. So, you render the PDF using `canvas` and then rotate the `canvas` itself. It might be a case that the parent container to your directive has overflow hidden or not resizing properly.

Could you give me the PDF you were using or even just the dimensions and what your DOM structure looks like. If you could replicate it with plunkr or codepen that would be amazing.

**Comment by apiraino** [comment]
thank you for your feedback we'll look into it, we'll try to reproduce the issue stripping all the code of the application surrounding the viewer.
