### ISSUE TITLE
Use bower_components/pdfjs-dist/build/pdf.js instead of pdf.combined.js

### ISSUE THREAD

**Issue by yurydelendik** [winkerVSbecks/angular-pdf-viewer#6]
Are there issues with using pdf.js / pdf.worker.js combo in angular?

**Comment by winkerVSbecks** [comment]
I think it should be fine. From the [https://github.com/mozilla/pdf.js#building-pdfjs](PDF.js readme):

> Both scripts are needed but only pdf.js needs to be included since pdf.worker.js will be loaded by pdf.js

Let me know if you come across any issues.

**Comment by yurydelendik** [comment]
Sorry I was not clear here, the readme code says to use pdf.combined.js, which is bad for the performance. So I was asking why it's recommend instead of normal pdf.js?

**Comment by winkerVSbecks** [comment]
I didn't pick the combined version for any particular reason – didn't realize there was a performance impact. 

I'll update the readme to say `pdf.js` instead. Thanks

**Comment by fespinoza** [comment]
for me it works better with pdf.combined.js, since I had some issues when using it with Grunt/Bower on the `dist` task

**Comment by winkerVSbecks** [comment]
@fespinoza shouldn't be the case – either should work just fine. Also, I'm using Gulp not Grunt for the `dist` task. If you give me a bit more info I can try to figure out what the issue was. Thanks

**Comment by igorlino** [comment]
ok, seems I got to the point where I have a related issue. Its of course a bit how i'm including the library. (It's a highly optimized build where all 3rd party are glued and compressed in 1 single file.)

In such scenario, the pdf.js will really not work anymore as that 3rd party lib has hardcoded the loading of the pdf.worker.js. Not only that, but it generates the url to get it in a very hacky way based on a derivate.  :-1: 

pdfjs-dist bower exposes:
  "main": [
    "build/pdf.js",
    "build/pdf.worker.js"
  ],

therefore my build most likely needs a workaround. If the bower would expose the pdf.combined.js that would solve my problem. But I think/feel its outside of the scope of this project.

**Comment by winkerVSbecks** [comment]
I don't have control over `pdfjs-dist` bower.json. You can try submitting a PR to them: https://github.com/mozilla/pdfjs-dist 

Alternatively you can provide overrides in your bower.json file:

```
"overrides": {
  "pdfjs-dist": {
    "main": [
       "build/pdf.js",
       "build/pdf.worker.js",
      ]
   }
}
```

**Comment by igorlino** [comment]
That was truly a masterful hint.  Thanks a lot.

While to find out this crazy issue, I got a very very indeep overview of the pdf.js and on top of this a small correction to fix it.

I don't think it's necessary to create them a PR. One would need another dist package I thinking.

Perhaps, it would be interesting for others about this small detail when using angular-pdf-viewer. As a way to further configure what dependency the really want.  

If you wish I could create the documentation and do a pull-request.

**Comment by fespinoza** [comment]
that was an awesome tip @winkerVSbecks 

and @igorlino awesome that you digged more on the issue... i have solved by just overwrite the pdfjs-dist/bower.json file under my bower_components... not the best solution ever but it worked

**Comment by yurydelendik** [comment]
> In such scenario, the pdf.js will really not work anymore as that 3rd party lib has hardcoded the loading of the pdf.worker.js

@igorlino not true, the location of the pdf.worker.js is specified in PDFJS.workerSrc

> for me it works better with pdf.combined.js, since I had some issues when using it with Grunt/Bower on the dist task

@fespinoza let me repeat my concern, "pdf.worker.js" include parser for PDF data (specifically large fonts and images) which requires a lot of CPU therefore it is designed to run in a web worker to avoid slow script warnings, "pdf.combined.js" includes this code (mostly for custom solutions and not recommended for use). Any recommendation to use it is wrong.

>  i have solved by just overwrite the pdfjs-dist/bower.json file under my bower_components..

I don't understand the issue you guys are having. PDF.js was designed to load "pdf.js" and, when document is being loaded, loaded web worker from PDFJS.workerSrc location and pass PDF data there.

Can you explain me that in dumb terms and provide an example to reproduce the issue? (Note that I'm not angular developer)

**Comment by igorlino** [comment]
@yurydelendik 
Perhaps the word 'hardcoded' is misleading.

I don't understand the background/interesnt behind your question, but I can give a bit more details...

As my previous analisys of the code of this library, the code does what it was written for. If you don't set PDFJS.workerSrc, and you endup needing the worker library, a script tag is created with a name that is partially hardcoded and also derivate that may endup being a funny thing that does not exist depending on circumstances. A failed attempt of dynamic loading the worker lib.

In dumb terms. The library "pdf.js" assumes certain loading situations, and assumes you behave well and include those libraries in conventional way. This disables some types of optimizations, that have not anything to do with angular.

To reproduce: create a single javascript file concatenating all the libraries you need. Assume you don't know the final name file of the library, its simply code that runs in the browser. (but of course its included into you main index.html for example)
In that single js file, you may include both pdf.js / pdf.worker.js. So, they are packed together.
In case the worker is needed, the code will throw an exception in the console.

The fix is out of scope of this "angular-pdf-viewer" project (probably also failed to explain that) and probably also out of scope of the "pdfjs-dist" bower.json
pdf.js code has to be improved in the dynamic loading of the worker library. Not everytime you have the luxury/wish/want to leave a library hack around your html/header/script tags to load another 3rd party library.

Cheers,
Igor

**Comment by yurydelendik** [comment]
> If you don't set PDFJS.workerSrc

In most of the case you shall specify PDFJS.workerSrc, unless you 100% sure automatic detection of pdf.worker.js will work.

> In that single js file, you may include both pdf.js / pdf.worker.js.

You shall not include pdf.js / pdf.worker.js in the single file. Worker is expecting only pdf.worker.js and main main page only pdf.js. Loading the same code in both increases memory and cpu consumption during parsing of the code.

> The fix is out of scope of this "angular-pdf-viewer" project (probably also failed to explain that) and probably also out of scope of the "pdfjs-dist" bower.json
pdf.js code has to be improved in the dynamic loading of the worker library. Not everytime you have the luxury/wish/want to leave a library hack around your html/header/script tags to load another 3rd party library.

We want pdfjs-dist bower.json be used with "angular-pdf-viewer" project. However all comments above does not help me understand the issue. That's why I'm asking for better example to demonstrate the issue. Does angular performs some magical loading of the web worker files or it hides all the resources paths so it's not possible to know then during execution?

**Comment by igorlino** [comment]
Interesting. I could not find such statements/restrictions about how to import the libraries in an standard html page. (https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions).

Yes, true. there are some performance problems loading such big javascript libraries (mainly pdf.worker.js)

No, as I mentioned before, angular is not related. It's related to my workflow.

In my gulp-based build workflow, all 3rd party js libs(>30) are nicely compressed into a single file. (using https://github.com/jonkemp/gulp-useref)
With the obvious advantage of avoiding making >30 HTTP calls, and instead only 1.

So, at the end I have a single "lib-2345325.js"  file (the number is random) and a single <script src="lib-2345325.js"> tag.

In an standard chrome browser installation, pdf.worker.js is nicely required, therefore pdf.js generates a new <script src="lib-2345325.worker.js"> tag, and colorfully fails to render anything at all.

2 possible workarounds in my build workflow:
1) directly use pdf.combined.js (via the bower.json overwrite)
2) set PDFJS.workerSrc to some fix server path & extend the build script, to add "handle-with-care" libraries individually (decreasing a bit the coolness the highly optimized single javascript). This would be the 1st library that has such requirement.

Angular, with respect of loading, behaves nearly the same as any other javascript code running in a browser. So I don't have concerns there.


For the sake of completeness. The automatic detection of pdf.worker.js in pdf.js ( line 7989 to 7997):

if (!PDFJS.workerSrc && typeof document !== 'undefined') {
  // workerSrc is not set -- using last script url to define default location
  PDFJS.workerSrc = (function () {
    'use strict';
    var scriptTagContainer = document.body ||
                             document.getElementsByTagName('head')[0];
    var pdfjsSrc = scriptTagContainer.lastChild.src;
    return pdfjsSrc && pdfjsSrc.replace(/\.js$/i, '.worker.js');
  })();
}

This code seems not much robust at all. It probably will break if you rename the file pdf.js, or also pdf.worker.js.

This could be potentially a problem when there are version updates. Typically user don't have any clue about browser caching. So they probably will get stuck to same version, if the naming of the files is by force/requirement static as you described in your previous comment.

So I think this part of the pdf.js is buggy and allows less flexibility for production deployment or highly optimized workflows.

**Comment by igorlino** [comment]
PART 2:

In an standard chrome browser installation, pdf.worker.js is nicely required, therefore pdf.js generates a new <script src="lib-2345325.worker.js"> tag, and colorfully fails to render anything at all.

The 2 possible workarounds in my build workflow:
1. directly use pdf.combined.js (via the bower.json overwrite)
2. set PDFJS.workerSrc to some fix server path & extend the build script, to add "handle-with-care" libraries individually (decreasing a bit the coolness the highly optimized single javascript). This would be the 1st library that has such requirement.

Angular, with respect of loading, behaves nearly the same as any other javascript code running in a browser. So I don't have concerns there.


For the sake of completeness. The automatic detection of pdf.worker.js in pdf.js ( line 7989 to 7997):

```
    if (!PDFJS.workerSrc && typeof document !== 'undefined') {
    // workerSrc is not set -- using last script url to define default location
    PDFJS.workerSrc = (function () {
    'use strict';
    var scriptTagContainer = document.body ||
        document.getElementsByTagName('head')[0];
    var pdfjsSrc = scriptTagContainer.lastChild.src;
    return pdfjsSrc && pdfjsSrc.replace(/\.js$/i, '.worker.js');
    })();
    }

```
This code seems not much robust at all. It probably will break if you rename the file pdf.js, or also pdf.worker.js.

This could be potentially a problem when there are version updates. Typically user don't have any clue about browser caching. So they probably will get stuck to same version, if the naming of the files is by force/requirement static as you described in your previous comment.

So I think this part of the pdf.js is buggy and allows less flexibility for production deployment or highly optimized workflows.

**Comment by yurydelendik** [comment]
> In my gulp-based build workflow, all 3rd party js libs(>30) are nicely compressed into a single file. (using https://github.com/jonkemp/gulp-useref)
With the obvious advantage of avoiding making >30 HTTP calls, and instead only 1.

(compatibility.js? and) pdf.js can/shall be a part of this common file, but not pdf.worker.js -- it shall be kept alone for loading by a web worker.

> The 2 possible workarounds in my build workflow:
> 2. set PDFJS.workerSrc to some fix server path...

That shall be done, yes. Generic PDF.js viewer do that. Most examples have it (at least comment) as well.

> This would be the 1st library that has such requirement.

Yes. Other libraries cannot or don't want to offload to heavy processing to a web worker in favor of better deployment. In case of PDF.js we have to do that, so we can provide better UX.

> So I think this part of the pdf.js is buggy and allows less flexibility for production deployment or highly optimized workflows.

Sure. How we can make it less buggy and more generic? My recommendation is to open an issue at https://github.com/mozilla/pdf.js with link to small example that fits your workflow and steps to reproduce the issue (better if non-angular developer could reproduce that).

**Comment by igorlino** [comment]
@yurydelendik  thanks Yury for the in-deep explanations.
I won't be able to reproduce officially at the moment, but if I get enough free time I may do some really interesting project due to: https://github.com/winkerVSbecks/angular-pdf-viewer/issues/14
It's more or less porting viewer.js into TypeScript.
Just don't know when precisely.

So, when the time comes, I may open an issue with concrete details.
