### ISSUE TITLE
pdfDelegate don't work in grunt build version

### ISSUE THREAD

**Issue by jairoGilC** [winkerVSbecks/angular-pdf-viewer#61]
Hi I have an Angular project, I'm using grunt serve to star the application in  my developer machine, her the package work perfect; but when generate the production version using the command `grunt build` the result code don't load the PDF and not show any error in the terminal

**Comment by winkerVSbecks** [comment]
`grunt build` is something specific to your project and not related to this library. Check the browser console for errors. The build task is probably not bringing in all required dependencies.
