### ISSUE TITLE
Toolbar doesn't hide

### ISSUE THREAD

**Issue by sasa72** [winkerVSbecks/angular-pdf-viewer#7]
Hi!
Although I set 
show-toolbar="false"

**Comment by sasa72** [comment]
Sorry, 
I came unintended to the "Comment Button" and do not know how to complete the issue, so I reopened it.

Although I set
             show-toolbar="false"
in the pdf-viewer-directive the toolbar is shown.

In the readme.md at section "directive" you wrote 
             show-nav="true"
instead of show-toolbar.

**Comment by winkerVSbecks** [comment]
@sasa72 sorry about that, fixed the typo

**Comment by opyate** [comment]
Same here. I tried both ```show-nav="false"``` and ```show-toolbar="false"``` but the toolbar always shows.

**Comment by imobach** [comment]
I've submitted a pull request (#8) that must solve that issue. I've not rebuilt the minified version, so you must launch a `gulp dist` to do that.

Hope it helps!
